// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type RegisterPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['register'], false>
}
type LoginPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], false>
}
type LogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type MeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['me'], false>
}
type PropertiesMineGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/properties_controller.ts').default['mine'], false>
}
type PropertiesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/properties_controller.ts').default['list'], false>
}
type PropertiesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/properties_controller.ts').default['show'], false>
}
type PropertiesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/property.ts')['createPropertyValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/properties_controller.ts').default['create'], true>
}
type PropertiesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/property.ts')['updateAnimalValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/properties_controller.ts').default['update'], true>
}
type PropertiesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/properties_controller.ts').default['delete'], false>
}
type ProfileEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profiles_controller.ts').default['edit'], false>
}
type ProfilesPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/profile.ts')['profileUpdateValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/profiles_controller.ts').default['update'], true>
}
type MessagesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/messages_controller.ts').default['index'], false>
}
type MessagesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/messages_controller.ts').default['show'], false>
}
type MessagesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/messages_controller.ts').default['store'], false>
}
type ConversationsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/conversations_controller.ts').default['index'], false>
}
type ConversationsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/conversations_controller.ts').default['create'], false>
}
export interface ApiDefinition {
  'register': {
    '$url': {
    };
    '$post': RegisterPost;
  };
  'login': {
    '$url': {
    };
    '$post': LoginPost;
  };
  'logout': {
    '$url': {
    };
    '$post': LogoutPost;
  };
  'me': {
    '$url': {
    };
    '$get': MeGetHead;
    '$head': MeGetHead;
  };
  'properties': {
    'mine': {
      '$url': {
      };
      '$get': PropertiesMineGetHead;
      '$head': PropertiesMineGetHead;
    };
    '$url': {
    };
    '$get': PropertiesGetHead;
    '$head': PropertiesGetHead;
    ':id': {
      '$url': {
      };
      '$get': PropertiesIdGetHead;
      '$head': PropertiesIdGetHead;
      '$put': PropertiesIdPut;
      '$delete': PropertiesIdDelete;
    };
    '$post': PropertiesPost;
  };
  'profile': {
    'edit': {
      '$url': {
      };
      '$get': ProfileEditGetHead;
      '$head': ProfileEditGetHead;
    };
  };
  'profiles': {
    '$url': {
    };
    '$put': ProfilesPut;
  };
  'messages': {
    '$url': {
    };
    '$get': MessagesGetHead;
    '$head': MessagesGetHead;
    ':userId': {
      '$url': {
      };
      '$get': MessagesIdGetHead;
      '$head': MessagesIdGetHead;
    };
    '$post': MessagesPost;
  };
  'conversations': {
    '$url': {
    };
    '$get': ConversationsGetHead;
    '$head': ConversationsGetHead;
    '$post': ConversationsPost;
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
